#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set luci.main.lang="auto"
	uci -q commit luci

	uci -q set system.@imm_init[0].lang="1"
	uci -q commit system
fi

uci -q set luci.main.socket="/var/run/ubus.sock"
uci -q commit luci

uci -q batch <<-EOF
        set system.@system[0].timezone='CST-8'
        set system.@system[0].zonename='Asia/Shanghai'

        delete system.ntp.server
        add_list system.ntp.server='ntp1.aliyun.com'
        add_list system.ntp.server='ntp.tencent.com'
        add_list system.ntp.server='ntp.ntsc.ac.cn'
        add_list system.ntp.server='time.apple.com'
EOF
uci commit system

#if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
#	uci -q set fstab.@global[0].anon_mount="1"
#	uci -q commit fstab

#	uci -q set system.@imm_init[0].anon_mount="1"
#	uci -q commit system
#fi

ln -sf "/sbin/ip" "/usr/bin/ip"

[ ! -e "/bin/bash" ] || sed -i "s|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g" "/etc/passwd"

sed -i 's|root::0:0:99999:7:::|root:$1$79txwdw6$7a2HrCa.13coApcg.7n/H/:20060:0:99999:7:::|g' /etc/shadow
sed -i 's|root:::0:99999:7:::|root:$1$79txwdw6$7a2HrCa.13coApcg.7n/H/:20060:0:99999:7:::|g' /etc/shadow


sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
